"""empty message

Revision ID: 101b804f3fea
Revises: 35bb02168854
Create Date: 2021-06-16 22:26:59.941484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101b804f3fea'
down_revision = '35bb02168854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'common_data', ['ci'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'common_data', type_='unique')
    # ### end Alembic commands ###
