"""empty message

Revision ID: 27712843e05a
Revises: 6eda599c39f4
Create Date: 2021-06-11 18:41:30.835810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27712843e05a'
down_revision = '6eda599c39f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cathedra', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('course', sa.Column('init_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'init_date')
    op.drop_column('cathedra', 'name')
    # ### end Alembic commands ###
