"""empty message

Revision ID: 438843d2e595
Revises: b3401d8019ae
Create Date: 2021-06-19 16:47:26.127698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438843d2e595'
down_revision = 'b3401d8019ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('code', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'course', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_column('course', 'code')
    # ### end Alembic commands ###
