"""empty message

Revision ID: 4f583717507b
Revises: 27712843e05a
Create Date: 2021-06-11 19:40:06.507148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f583717507b'
down_revision = '27712843e05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('title', sa.String(length=40), nullable=True))
    op.add_column('notes', sa.Column('note', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'note')
    op.drop_column('course', 'title')
    # ### end Alembic commands ###
