"""empty message

Revision ID: 5a1f02b437ad
Revises: 438843d2e595
Create Date: 2021-06-21 12:10:24.519920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1f02b437ad'
down_revision = '438843d2e595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grade_student_id_fkey', 'grade', type_='foreignkey')
    op.drop_column('grade', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('grade_student_id_fkey', 'grade', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###
