"""empty message

Revision ID: 6eda599c39f4
Revises: b82a78360efd
Create Date: 2021-06-11 12:22:16.060180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eda599c39f4'
down_revision = 'b82a78360efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=40), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=40), nullable=True),
    sa.Column('residence', sa.String(length=120), nullable=True),
    sa.Column('career', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('evaluation_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_plan_id'], ['evaluation_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['common_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['common_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cathedra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('career', sa.String(length=40), nullable=False),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor_student_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cathedra_asigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('cathedra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cathedra_id'], ['cathedra.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cathedra_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cathedra_id'], ['cathedra.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('notes')
    op.drop_table('course')
    op.drop_table('cathedra_asigns')
    op.drop_table('professor_student_rel')
    op.drop_table('cathedra')
    op.drop_table('student')
    op.drop_table('professor')
    op.drop_table('evaluation')
    op.drop_table('evaluation_plan')
    op.drop_table('common_data')
    # ### end Alembic commands ###
