"""empty message

Revision ID: 7d43b7adb170
Revises: 933400ef34a2
Create Date: 2021-06-17 18:00:15.526962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d43b7adb170'
down_revision = '933400ef34a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cathedra_name_key', 'cathedra', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cathedra_name_key', 'cathedra', ['name'])
    # ### end Alembic commands ###
