"""empty message

Revision ID: a6a7838e88b1
Revises: 1ebd745ae92c
Create Date: 2021-06-13 10:27:40.583503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a7838e88b1'
down_revision = '1ebd745ae92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cathedra', sa.Column('code', sa.String(length=4), nullable=False))
    op.create_unique_constraint(None, 'cathedra', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cathedra', type_='unique')
    op.drop_column('cathedra', 'code')
    # ### end Alembic commands ###
